name: Scrapping data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setting up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install requirements and run script
        run: |
          pip install -r src/requirements.txt
          python src/extractPlayersStats.py
    
      - name: Commit scrapping
        run: |
          git config --global user.name 'guilhermetheis'
          git config --global user.email 'guilhermetheis15@gmail.com'
          git add .
          git commit -am "update data"
          git push
